### PR TITLE
Fix #88 - Update PartOneStep06Controller.java

### LINKED ISSUE #88: DM56 Failure Criteria future enhancement
From j1939-84 created by [ericthomasswenson](https://github.com/ericthomasswenson): Equipment-and-Tool-Institute/j1939-84#819  

Draft new failure criteria for the DM56 (Engine Family) PG to fail 2024MY engines for lack of support.

### PR DESCRIPTION
**Pull request by mmschaefer**
Check the engine year compliance per update covered in SOW.

### CODE REVIEW

File: src/org/etools/j1939_84/controllers/part01/Part01Step06Controller.java [hunk 1]
```diff
@@ -60,14 +60,18 @@ protected void run() throws Throwable {
 
         // 6.1.6.1.a. Global DM56 (send Request (PGN 59904) for PGN 64711 (SPNs 5844 and 5845)).
         List<DM56EngineFamilyPacket> packets = getCommunicationsModule().requestDM56(getListener());
+        int engineModelYear = getDataRepository().getVehicleInformation().getEngineModelYear();
+
         if (packets.isEmpty()) {
             getListener().onResult("6.1.6.1.a - DM56 is not supported");
+            if (engineModelYear > 2024) {
+                addFailure("6.1.6.2.f - MY2024+ Engine does not support DM56");
+            }
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/controllers/part01/Part01Step06Controller.java:70]: I would suggest adding an `else` here so we don’t publish both the `onResult` and the failure.

**Review by gumbelmj — APPROVED** [review]
