### PR TITLE
Fix #13 Update Part 01 Step 08 to latest spec rev, update test and comment

### LINKED ISSUE #13: Fix & break up the test for Part 01 Step 08
Unit tests for Part 01 Step 08 need to broken down to one error per test and the test need to be update to cover all lines of code.

### PR DESCRIPTION
**Pull request by mmschaefer**
Fix #13 - Updates for the latest revision of the requirements, add testing, documentation evidence and java doc comments

### CODE REVIEW

File: src/org/etools/j1939_84/controllers/part01/Part01Step08Controller.java [hunk 1]
```diff
@@ -71,9 +72,18 @@ protected void run() throws Throwable {
         globalDM20s.forEach(this::save);
 
         // 6.1.8.2.a. Fail if minimum expected SPNs are not supported (in the aggregate response for the vehicle)
-        // per section A.4, Criteria for Monitor Performance Ratio Evaluation.
+        // per section A.4. When a numerator and denominator are provided as FFFF(h) and FFFF(h), the monitor identified
+        // in the label SPN shall be considered to be unsupported.
         Set<Integer> dm20Spns = globalDM20s.stream()
                                            .flatMap(dm20 -> dm20.getRatios().stream())
+                                           .peek(dm20 -> {
+                                               if (dm20.getNumerator() == 0xFF &&
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/controllers/part01/Part01Step08Controller.java]: 1. This needs to compare the numerator and denominator to 0xFFFF
2. This should be a filter.  The new logic is to consider the SPN to be unsupported if both the numerator and denominator are 0xFFFF.  That means the SPN is removed from the list.  Then the rest of the logic will take care of the failure. There's no need to report a new failure here.

**Review by gumbelmj — CHANGES_REQUESTED** [review]

File: src-test/org/etools/j1939_84/controllers/part01/Part01Step08ControllerTest.java [hunk 2]
```diff
@@ -325,13 +352,49 @@ public void testNoSpnNPacketsMatch() {
...
 
+    /**
+     * Test packet with expected SPNs returned for global or destination specific
+     * DM20 request - spark engine
+     */
+    @Test
+    @TestDoc(value = @TestItem(verifies = "6.1.8.2.a", description = "When a numerator and denominator are provided as FFFFh and FFFFh, the monitor identified in the label SPN shall be considered to be unsupported"))
+    public void testAllNumeratorAndDenominatorAllFs() {
+        int moduleAddress = 0;
+        int spn = 524287;
```
Comment (gumbelmj) [inline src-test/org/etools/j1939_84/controllers/part01/Part01Step08ControllerTest.java]: The test should have detected that SPN 524287 wasn’t supported. I think this SPN should be switched to one of the required SPNs.  I’d write the test first with good values and no failures, then change the values to 0xFFFF to produce the failure.

**Review by gumbelmj — CHANGES_REQUESTED** [review]

File: src-test/org/etools/j1939_84/controllers/part01/Part01Step08ControllerTest.java (hunk 2 above)
Comment (mmschaefer) [reply src-test/org/etools/j1939_84/controllers/part01/Part01Step08ControllerTest.java]: [Fixed](https://github.com/SolidDesignNet/j1939-84/pull/15/commits/ee27fabc261386b5077c7010f9885f660d890a86)

**Review by gumbelmj — APPROVED** [review]
