### PR TITLE
Fix #84 - Save the results for use later in testing

### LINKED ISSUE #84: Add DM20 test in Part 12
From j1939-84 created by [ericthomasswenson](https://github.com/ericthomasswenson): Equipment-and-Tool-Institute/j1939-84#1010  

Add DM20 test in Part 12 as an accommodation for variances in DM20 housekeeping that may occur between test 11.8 and 12.9.

**_6.12.9 DM20: Monitor Performance Ratio
6.12.9.1 Actions 
a. DS DM20 [send Request (PG 59904) for PG 49664 (SPs 3048-3049, 3066-3068)] to ECUs that reported DM20 data earlier in Part 11.
b. If no response [transport protocol RTS or NACK(Busy) in 220 ms], then retry DS DM20 request to the OBD ECU. [Do not attempt retry for NACKs that indicate not supported]. 
c. Record responses for use in part 12 test 11 (formerly 12.9.2).
6.12.9.2 Fail Criteria 
a. Fail if retry was required to obtain DM20 response. 
b. Fail if any response indicates that the general denominator (SP 3049) is greater by more than 1 when compared to the general denominator received in Part 11 test 5. 
c. Fail if NACK received from OBD ECUs that previously provided a DM20 message. 
6.12.9.3 Warn Criteria 
a. Warn if any response indicates an individual numerator or denominator that is greater than the corresponding values received in Part 11 test 8. 
b. Warn if any ECU response shows: 
i. any monitor denominator greater than the general denominator;  
ii. general denominator greater than the ignition cycle counter (SP 3048); or 
iii. if any numerator greater than the ignition cycle counter. 
c. Compare all values to values recorded in part 11 test 8. 
i. Warn if any value (numerator, denominator, or ignition cycle counter) is less than their corresponding value in part 11 test.
d. If more than one ECU reports DM20 data, warn if general denominators or ignition cycle counts do not match from all ECUs._**

6.11.8 DM20: Monitor Performance Ratio 
6.11.8.1 Actions 
a. DS DM20 [(send Request (PG 59904) for PG 49664 (SPs 3048-3049, 3066-3068)]) to ECUs that reported DM20 data earlier in this part. 
b. If no response [(transport protocol RTS or NACK(Busy) in 220 ms]), then retry DS DM20 request to the OBD ECU. ([Do not attempt retry for NACKs that indicate not supported]).
**_c. Record responses for use in Part 12 test 9_**

### PR DESCRIPTION
**Pull request by mmschaefer**
Update the part 12 step 8 to save the results gathered for use later in the testing.

### CODE REVIEW

File: src/org/etools/j1939_84/controllers/part11/Part11Step08Controller.java [hunk 1]
```diff
@@ -101,7 +99,7 @@ protected void run() throws Throwable {
         List<Integer> missingAddresses = determineNoResponseAddresses(dsResults, addresses);
         missingAddresses.stream()
                         .map(address -> getCommunicationsModule().requestDM20(getListener(), address))
-                        .forEach(dsResults::add);
+                        .peek(dsResults::add);
```
Comment (gumbelmj) [inline src/org/etools/j1939_84/controllers/part11/Part11Step08Controller.java]: You can’t change this to `.peek()`. The `.forEach()` is a terminal operation.  Without the terminal operation, the stream will never start emitting values.

**Review by gumbelmj — CHANGES_REQUESTED** [review]

File: src/org/etools/j1939_84/controllers/part11/Part11Step08Controller.java (hunk 1 above)
Comment (mmschaefer) [reply src/org/etools/j1939_84/controllers/part11/Part11Step08Controller.java]: Already caught.

**Review by gumbelmj — APPROVED** [review]
