### PR TITLE
Part 01 Step 09 Updates

### LINKED ISSUE #14: Fix & break up the test for Part 01 Step 09
Unit tests for Part 01 Step 09 need to broken down to one error per test and the test need to be update to cover all lines of code.

### PR DESCRIPTION
**Pull request by mmschaefer**
Fix #14 - Updates for the latest revision of the requirements, add testing, documentation evidence and java doc comments

### CODE REVIEW

File: src-test/org/etools/j1939_84/controllers/part01/Part01Step09ControllerTest.java [hunk 1]
```diff
@@ -510,42 +561,55 @@ public void testMakeFieldMoreThanFiveCharacters() {
         assertEquals("Function 0 ECU is Engine #1 (0)" + NL, listener.getResults());
     }
 
+    // /**
```
Comment (gumbelmj) [inline src-test/org/etools/j1939_84/controllers/part01/Part01Step09ControllerTest.java:564]: why is this commented out?

**Review by gumbelmj — APPROVED** [review]
